name: pos_kozen_printer
description: Flutter plugin for KOZEN printers on TUU/Haulmer POS PRO2 devices. Easily print text and images on thermal printers.
version: 0.0.2
homepage: https://github.com/jOrdenesC/pos_kozen_printer
repository: https://github.com/jOrdenesC/pos_kozen_printer
issue_tracker: https://github.com/jOrdenesC/pos_kozen_printer/issues

environment:
  sdk: ^3.8.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kozen.pos_kozen_printer
        pluginClass: PosKozenPrinterPlugin
